languageCode = "zh-tw"
languageName = "Mandarin"
displayName = "zh-tw"
isoCode = "zh-tw"
weight = 1
rtl = false

title = ":shinto_shrine:小鶴の宇宙:shinto_shrine:"
logo = "img/tsurumoto_logo.png"
description = "熱衷於分享不動產資訊＆生活＠小鶴經營的小鶴の宇宙"
copyright = "Copy, Tsurumoto @2023"

dateFormat = "Mon, Jan 02, 2006"

[author]
  name = "小鶴 Tsurumoto"
  image = "img/tsurumoto_logo.jpg"
  headline = "熱衷於分享不動產資訊＆生活"
  bio = "熱愛紫微斗數與不動產的工程師。長期關注台灣的不動產資訊與發展，不定期分享業內的看法以及有興趣的建案"
  #links = [
  #   { link = "https://nunocoracao.github.io/blowfish/" },
  #   { github = "https://github.com/nunocoracao/blowfish" },
  #   { twitter = "https://twitter.com/burufugu" },
  # ]
