# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Articles"
  pageRef = "posts"
  weight = 1

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 10


[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  identifier = "web"
  pre = "Dcard"
  url = "https://www.dcard.tw/@tsurumoto"
  weight = 40
[[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@tsurumoto_universe"
  weight = 60

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/tsurumoto_ziwei/"
  weight = 50

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/tsurumoto-shi/home"
  weight = 70
# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
